<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_The Watty Awards</name>
   <tag></tag>
   <elementGuidId>a4c03374-20fe-4074-8cb0-f90e8192964e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.c97t-</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'https://www.wattpad.com/awards' and (text() = 'The Watty Awards' or . = 'The Watty Awards')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='community-dropdown']/div[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>301068dc-94e7-4dea-9514-1df7a4c8d584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c97t-</value>
      <webElementGuid>e4a0f55a-bdbd-4416-bd48-3a41d3ac5a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.wattpad.com/awards</value>
      <webElementGuid>ab198151-a7cf-43ba-a8bb-3a282a9b1380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>d9870b1f-fcb0-4a99-b2d5-f02a59fbdb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>9ff6b931-2904-4106-996a-a6449163d170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Watty Awards</value>
      <webElementGuid>50e623f3-c169-485a-9840-f20864a86357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;community-dropdown&quot;)/div[@class=&quot;MaVh4 V-8Oa&quot;]/ul[@class=&quot;_0X2RS&quot;]/li[@class=&quot;fnWge&quot;]/a[@class=&quot;c97t-&quot;]</value>
      <webElementGuid>e5425cb6-8e86-47b8-bcfd-2d4e12d4a798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='community-dropdown']/div[2]/ul/li/a</value>
      <webElementGuid>81e02083-d11f-4685-8228-0a34022a6117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'The Watty Awards')]</value>
      <webElementGuid>d5f4a23f-4beb-4c62-99a5-de342e57f2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community'])[1]/following::a[1]</value>
      <webElementGuid>e5afbb83-13c2-49b8-a076-0ed465d09865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse'])[1]/following::a[1]</value>
      <webElementGuid>24be7d7b-ca0b-4d17-94f7-df065b8d2716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community Happenings'])[1]/preceding::a[1]</value>
      <webElementGuid>5a5b6da2-86b6-442f-82ee-32a4c09eead1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wattpad Ambassadors'])[1]/preceding::a[2]</value>
      <webElementGuid>ff3bb36d-a2a2-452c-bb86-1793943d91be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The Watty Awards']/parent::*</value>
      <webElementGuid>4d5a9d6f-4bec-4542-b7e1-e8100ed7bb8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.wattpad.com/awards')]</value>
      <webElementGuid>f3e32020-56ea-421d-8c30-7e5bff8cce25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>05d251be-7349-4e8c-b176-95496a006bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.wattpad.com/awards' and (text() = 'The Watty Awards' or . = 'The Watty Awards')]</value>
      <webElementGuid>cbc06da1-7f30-4645-b37b-d87b0c7a54d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
