<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Wattpad Ambassadors</name>
   <tag></tag>
   <elementGuidId>c9adff8e-fecb-4e1d-a860-a22c5c337507</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'https://www.wattpad.com/823619' and (text() = 'Wattpad Ambassadors' or . = 'Wattpad Ambassadors')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='community-dropdown']/div[2]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>03872918-564e-4520-905d-16615751a58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c97t-</value>
      <webElementGuid>4c594c10-e139-4ef6-8549-11a33f129b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.wattpad.com/823619</value>
      <webElementGuid>cd94fe5a-81bd-4349-8c57-bc683ecac834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>1803501d-f239-4749-83f8-8498bd8af20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>eb6c73fe-c9ee-4d18-8adc-20e5e4d38fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wattpad Ambassadors</value>
      <webElementGuid>41f1df86-a673-4481-a3dd-6e85bf8dad10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;community-dropdown&quot;)/div[@class=&quot;MaVh4 V-8Oa&quot;]/ul[@class=&quot;_0X2RS&quot;]/li[@class=&quot;fnWge&quot;]/a[@class=&quot;c97t-&quot;]</value>
      <webElementGuid>bd23a603-57d8-454b-875b-396628eef834</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='community-dropdown']/div[2]/ul/li[3]/a</value>
      <webElementGuid>4956768c-91b3-46fc-afd9-a05998610cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Wattpad Ambassadors')]</value>
      <webElementGuid>8160e8f1-0582-48d2-9821-18586804c158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community Happenings'])[1]/following::a[1]</value>
      <webElementGuid>419ad583-aa20-4592-9016-585bd16a7993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Watty Awards'])[1]/following::a[2]</value>
      <webElementGuid>79f468bf-3ef9-4e00-b25e-9fe685dc0a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write'])[1]/preceding::a[1]</value>
      <webElementGuid>cb14e34c-5d1b-415b-8fda-2a97aff97f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Premium'])[1]/preceding::a[1]</value>
      <webElementGuid>cf3614ca-6018-4d4d-9dbd-b94c3e0d6348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wattpad Ambassadors']/parent::*</value>
      <webElementGuid>1c0de4c7-01be-4068-a936-3c205df6bc9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.wattpad.com/823619')]</value>
      <webElementGuid>a8f77ccd-a605-446f-aa79-72568cdf807f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>75d9613a-648b-4ac0-818d-3ea88d42305f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.wattpad.com/823619' and (text() = 'Wattpad Ambassadors' or . = 'Wattpad Ambassadors')]</value>
      <webElementGuid>29aecb87-49b9-4a02-86a5-fd6bb8f0b65d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
