<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Supernatural Love</name>
   <tag></tag>
   <elementGuidId>ed4ab7b8-8cf6-4c05-ba48-4506a7385546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Supernatural Love 💘🦇' or . = 'Supernatural Love 💘🦇')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='discover-dropdown']/div[2]/div[2]/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a72fd199-6a05-4c9e-8a71-76a3c04907a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c97t-</value>
      <webElementGuid>5748dbf2-6db4-492b-9c38-a0e1fef900c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/featured/1689737617</value>
      <webElementGuid>ebf92a43-659a-4b7e-bf71-4296b45b17cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>409642c4-c984-43fa-a8b1-202e97b644e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>c13e4a0a-a8c2-4454-bf9c-f991d7b34969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Supernatural Love 💘🦇</value>
      <webElementGuid>3fec4ac9-d6c5-4cf8-b074-fee3751bc5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;discover-dropdown&quot;)/div[@class=&quot;MaVh4 V-8Oa MllQ5&quot;]/div[@class=&quot;_2aB5H&quot;]/ul[@class=&quot;_0X2RS&quot;]/li[@class=&quot;fnWge&quot;]/a[@class=&quot;c97t-&quot;]</value>
      <webElementGuid>f0320680-685d-4430-a0aa-530f8a742602</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='discover-dropdown']/div[2]/div[2]/ul/li[4]/a</value>
      <webElementGuid>3fd795f5-d40c-4f1f-9488-2b3f095d825c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Supernatural Love 💘🦇')]</value>
      <webElementGuid>b4010c23-397e-4e68-878c-5aef7a26ed96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campus Romances 💞📚'])[1]/following::a[1]</value>
      <webElementGuid>c02ccb28-084e-4c22-af78-5e4f3da248ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reading Radar'])[1]/following::a[2]</value>
      <webElementGuid>ea29122f-afed-433e-8b70-526eb49d848e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stories by Her'])[1]/preceding::a[1]</value>
      <webElementGuid>e6f7a9f5-db52-443d-b0e0-10513a983489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wattpad WEBTOON Studios Hits ⭐'])[1]/preceding::a[2]</value>
      <webElementGuid>ec0fefa9-06ce-4fc1-a416-69fb78141c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Supernatural Love 💘🦇']/parent::*</value>
      <webElementGuid>9885641c-4581-4370-b15e-8dc572fec379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/featured/1689737617')]</value>
      <webElementGuid>08cd303a-0e6f-4a0f-a1fb-fa65fc1b2089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[4]/a</value>
      <webElementGuid>5800faeb-f715-44b3-9864-77aa93185b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/featured/1689737617' and (text() = 'Supernatural Love 💘🦇' or . = 'Supernatural Love 💘🦇')]</value>
      <webElementGuid>ebcf3019-544d-4f78-add0-7e54c5db27d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
