<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Terms</name>
   <tag></tag>
   <elementGuidId>b68f9d0f-cbeb-478e-bc5a-642c8a19b3f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a._7TWJ4.sB6J0._58Jsq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Terms')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f97abfea-bbf3-4712-b289-b1cfe8a30728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7TWJ4 sB6J0 _58Jsq</value>
      <webElementGuid>452d704c-d8e7-41fb-8ad2-8f35cc04dd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://policies.wattpad.com/terms</value>
      <webElementGuid>7fc4e2c3-cddd-470a-aad9-54130ee87af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>0d6106b3-c35c-4991-8d86-2d46930da1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terms</value>
      <webElementGuid>c2b59d6f-b589-4df2-883e-60b55a49f723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;theme-6&quot;]/footer[@class=&quot;KsomK PUdBR _3iH-u&quot;]/ul[@class=&quot;VT-tn ehTVt _96aZR PUdBR _3iH-u&quot;]/li[1]/a[@class=&quot;_7TWJ4 sB6J0 _58Jsq&quot;]</value>
      <webElementGuid>39317ab5-77b0-490c-867c-fde260a5dd18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Terms')]</value>
      <webElementGuid>7d9cf79a-f548-4928-be74-a1cf3a635798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press'])[1]/following::a[1]</value>
      <webElementGuid>42d947b2-134c-4208-8f7c-e8b4216de958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs'])[1]/following::a[2]</value>
      <webElementGuid>3d71bdeb-9899-4fd5-afdc-8b8704099e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/preceding::a[1]</value>
      <webElementGuid>b7daf8ce-bee3-4da5-831c-529d3d68320c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Policy'])[1]/preceding::a[2]</value>
      <webElementGuid>fb27aba3-c319-4853-85fb-3680724ff507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terms']/parent::*</value>
      <webElementGuid>4314d87b-1147-4f16-9297-7e82cf93af64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://policies.wattpad.com/terms')]</value>
      <webElementGuid>9e51ea62-32ca-4797-95f4-4db772424e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a</value>
      <webElementGuid>0f00b92e-b384-4186-9035-699afe7c9a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://policies.wattpad.com/terms' and (text() = 'Terms' or . = 'Terms')]</value>
      <webElementGuid>cb6ff937-f343-4abe-9c15-2ab2a7912023</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
