<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yes, I have read and agree to Wattpads Terms of Service and Privacy Policy</name>
   <tag></tag>
   <elementGuidId>b5a29cd2-f92c-473c-956b-80b95abbc961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = concat(&quot;Yes, I have read and agree to Wattpad&quot; , &quot;'&quot; , &quot;s Terms of Service and Privacy Policy.&quot;) or . = concat(&quot;Yes, I have read and agree to Wattpad&quot; , &quot;'&quot; , &quot;s Terms of Service and Privacy Policy.&quot;))]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#policy-consent > span.ckEo7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='policy-consent']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0f339035-7583-4e67-b01f-ebcc99c2d294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ckEo7</value>
      <webElementGuid>a582fe2f-4354-42b6-8f79-62c69c8c6646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes, I have read and agree to Wattpad's Terms of Service and Privacy Policy.</value>
      <webElementGuid>6bf538ca-5727-44fe-92fb-67fd2c9789b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup-form&quot;)/div[7]/div[@class=&quot;MUv--&quot;]/label[1]/div[@class=&quot;mBXnn&quot;]/div[@id=&quot;policy-consent&quot;]/span[@class=&quot;ckEo7&quot;]</value>
      <webElementGuid>3ff4e1b1-22bd-4dc2-857e-e622aff61b0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='policy-consent']/span</value>
      <webElementGuid>cf5ae7e9-08b5-42f9-bfef-26c885f4aecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get story updates, announcements, offers, and more via email. Unsubscribe anytime.'])[1]/following::span[1]</value>
      <webElementGuid>d16669b1-885e-4705-8645-23f8bd47211a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/label/div/div/span</value>
      <webElementGuid>abf31bcc-8af0-4ed8-a7bb-e0548979c2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = concat(&quot;Yes, I have read and agree to Wattpad&quot; , &quot;'&quot; , &quot;s Terms of Service and Privacy Policy.&quot;) or . = concat(&quot;Yes, I have read and agree to Wattpad&quot; , &quot;'&quot; , &quot;s Terms of Service and Privacy Policy.&quot;))]</value>
      <webElementGuid>fa8d3682-7acf-4d44-9030-2341489994d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
