<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS - Sign In</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5f573c37-99fb-4882-bbd0-20d5243e9450</testSuiteGuid>
   <testCaseLink>
      <guid>1e23a2c6-7690-46bd-add6-d7afcb04a697</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SC004 - Sign In with Email/TC001 - Login with valid account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffc99040-5e55-4c22-90a3-584296b02108</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1929c252-71d7-43e4-bae6-33847b148e19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0286635a-3768-495c-8f49-4835b47c6c42</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c85f7118-fa95-480d-9ac5-1be0bddfe348</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SC004 - Sign In with Email/TC002 - Login with show password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>653743de-22b6-467d-ac1e-1e3c60504216</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8389d8c-e849-4426-a2a5-fe1991af9b0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0956ed37-8714-431f-9bef-d7ba2315a1c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4224294c-34ff-4cf3-87da-47fb84ec52ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SC004 - Sign In with Email/TC003 - Login with hide password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28299833-2f36-4677-9777-d8d0bcf28536</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>610695f9-c53d-45b2-9ee2-fbc1075846ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86af5cd1-3a11-47d7-9b8e-42e8db64308c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e2ccf93-c063-4a08-ad96-14bacad5385b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SC004 - Sign In with Email/TC004 - Login with invalid account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3891b4fe-500b-40c5-b662-9242c76ffde9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55db2ce8-e5ea-4c19-8fd5-a123023255cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e06f6aa-fe49-4d7d-8af8-b50fd4606274</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>103e46ba-f566-419b-82d2-16111a55460d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SC004 - Sign In with Email/TC005 - Login without filling email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5fcf2b4-eca7-4d56-9658-fe01e3a4e65e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b883c074-0c70-4211-a40e-809f06d1ffda</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8774514f-5738-44b1-b381-991a892b3d35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SC004 - Sign In with Email/TC006 - Login without filling password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32408fdf-7f55-442f-83de-a0f387edf899</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d51c2c05-97fd-4085-8c7d-a6d5e4b59b71</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
