<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Browse</name>
   <tag></tag>
   <elementGuidId>72c94f9e-100c-4024-9fb8-dcfb5582a0fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.DMdhq.sPJMO</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Browse' or . = 'Browse')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='discover-dropdown']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>340ae689-cf1f-4cea-8c9b-d2f938c41cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DMdhq sPJMO</value>
      <webElementGuid>328df767-3d10-4a02-b414-db695fc77b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Browse</value>
      <webElementGuid>d4fc330c-90a4-4794-958f-68daae72fc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;discover-dropdown&quot;)/button[@class=&quot;DMdhq sPJMO&quot;]</value>
      <webElementGuid>5b54d2ef-c8cc-4b3d-9edc-74d6baa8383c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='discover-dropdown']/button</value>
      <webElementGuid>8a1e0b96-9822-4008-855f-789892e10889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community'])[1]/preceding::button[1]</value>
      <webElementGuid>c7db2d5e-e8df-4f03-a1d4-ae9645eaa3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write'])[1]/preceding::button[3]</value>
      <webElementGuid>d0dcd7ea-294d-4e10-ba64-20f690af5564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Browse']/parent::*</value>
      <webElementGuid>6797c9a5-5198-4bf8-ad38-5698dbccd4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>e7d99a22-2a28-4214-8a53-9ce70135759f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Browse' or . = 'Browse')]</value>
      <webElementGuid>972e4d2d-a701-4bb7-8cb9-af5d2f36e1e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
