<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email or username</name>
   <tag></tag>
   <elementGuidId>27541a32-07fa-430d-afc2-0c6756c7db03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-username</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'login-username' and @placeholder = 'Email or username' and @name = 'username']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e714570f-f082-4ca7-aa91-054278ad0fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5203c85-ca11-4025-bbf3-f028d2de0696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-username</value>
      <webElementGuid>16451ced-f62f-4ba5-8319-377a0848e48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email or username</value>
      <webElementGuid>1dc2b857-6be7-417c-806d-d56cb82ad096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>f1814a85-c8fb-4c43-8675-470f69e4dcf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9T55T</value>
      <webElementGuid>08c4cdda-b27d-48fe-89a6-b1f50ec2a6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-username&quot;)</value>
      <webElementGuid>74aac092-ff3f-4dfa-8806-a917ab297751</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-username']</value>
      <webElementGuid>1103f40a-b734-4984-956d-a8d930b096f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div/div/input</value>
      <webElementGuid>cb16b2f0-2721-4c70-89e9-5767a3e836f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>cddf32f1-6a0e-40f3-bec6-73938015918a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'login-username' and @placeholder = 'Email or username' and @name = 'username']</value>
      <webElementGuid>2a13e32c-943f-4c0c-8efe-adf863f9e156</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
