<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Writing Contests</name>
   <tag></tag>
   <elementGuidId>2c64cb86-e0d3-4306-a995-983c264c4136</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.wD0Bj > h4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='GetDiscovered']/div/div/a/div[2]/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>1e6a50de-b400-406f-9953-28bf96386a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>55b518f9-1af4-43d3-a185-2315fc38b170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Writing Contests</value>
      <webElementGuid>08eeafc7-fe80-4b6f-aa7f-f39023bc28bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GetDiscovered&quot;)/div[@class=&quot;Ts6Uf&quot;]/div[@class=&quot;d2Hid&quot;]/a[@class=&quot;tJ8VN&quot;]/div[@class=&quot;wD0Bj&quot;]/h4[1]</value>
      <webElementGuid>488ccee5-bfa6-4c6f-a3f2-1e3ab3bef59e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GetDiscovered']/div/div/a/div[2]/h4</value>
      <webElementGuid>0fb91391-1533-4244-b16c-ad4d1bb68899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Discovered'])[1]/following::h4[1]</value>
      <webElementGuid>f56ab1c8-3d06-496f-8c4e-05cc4bf02d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Reading'])[16]/following::h4[1]</value>
      <webElementGuid>b10c9e85-7d04-4eec-8b3a-0a96507d58e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Wattys'])[1]/preceding::h4[1]</value>
      <webElementGuid>518178d3-0903-4317-965f-7845ca1c2af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wattpad Picks'])[1]/preceding::h4[2]</value>
      <webElementGuid>a46d7a84-c5a4-4d4f-b9b3-74343ea6f15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Writing Contests']/parent::*</value>
      <webElementGuid>9931d37e-8411-43c4-b627-3a49172963ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h4</value>
      <webElementGuid>97fa23fb-488f-45fa-ab13-f9151311c3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Writing Contests' or . = 'Writing Contests')]</value>
      <webElementGuid>81488d62-d0bc-4330-a4fb-a1fc3c2aaa44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
