<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel</name>
   <tag></tag>
   <elementGuidId>482922c5-72b8-4c9a-af1e-fb1f3d1fc8ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.HuEB9._7Lv9u</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='forgot-password-form']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a7c3efc3-90db-4cdc-9d11-68b105b29748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cancel-btn</value>
      <webElementGuid>96360c0d-e299-48a9-a87a-16155d696d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>HuEB9 _7Lv9u</value>
      <webElementGuid>101dede9-d30e-439f-9ba7-8d343d7e4960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>77b9b96b-489a-4d1e-9dd5-0bb0da440e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.wattpad.com/login?nextUrl=https://www.wattpad.com/home</value>
      <webElementGuid>b5356c94-7ea6-4b10-8eac-b4ea2656760b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>849cc9b7-1127-48ff-9aca-931bc8a228c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgot-password-form&quot;)/div[@class=&quot;hF3B-&quot;]/a[@class=&quot;HuEB9 _7Lv9u&quot;]</value>
      <webElementGuid>5533f731-d5cf-4e28-b018-08d0530e54a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='forgot-password-form']/div[2]/a</value>
      <webElementGuid>68646417-e0f0-4cec-b5b0-54da83a5f02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel')]</value>
      <webElementGuid>bd1daa42-a84e-474a-9b68-72acff15187d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wattpad Support'])[1]/following::a[1]</value>
      <webElementGuid>7b6cf577-b22b-4995-8eba-fefaa5cbfa57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wattpad Originals'])[1]/preceding::a[6]</value>
      <webElementGuid>6456219e-d727-42b4-b01f-a36d24c369c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Premium'])[2]/preceding::a[7]</value>
      <webElementGuid>ca4b24eb-ce85-4173-a7a2-96be6e713ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>c1e6983a-0c1c-43e3-a29a-d00ab82ff77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.wattpad.com/login?nextUrl=https://www.wattpad.com/home')]</value>
      <webElementGuid>1ed7e9dd-ec36-4f07-868c-e631fdb55da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>c08c9a40-0176-41cb-a9b9-d170afaa7cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.wattpad.com/login?nextUrl=https://www.wattpad.com/home' and (text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>05b00c70-c212-4e2a-bae7-4b9f722aa2db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
