<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username or email</name>
   <tag></tag>
   <elementGuidId>601ec6a8-4145-4665-be53-e1a6d15798a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#forgot-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='forgot-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9257fa3d-acd6-4acd-b4bb-5b86605ce9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad132f01-5335-4923-97b9-ca55a0545c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forgot-email</value>
      <webElementGuid>48739ebf-67a2-416f-96a1-3f086cc4d76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username or Email</value>
      <webElementGuid>5462106b-609b-49b1-9d6f-a7dacb52b0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ca042f05-005a-41f8-959e-4d6389b7b054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9T55T</value>
      <webElementGuid>beb83981-0659-4aa8-968a-9c2e485f8815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgot-email&quot;)</value>
      <webElementGuid>79f4aaa1-e740-4284-b2bb-28653c59a1da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='forgot-email']</value>
      <webElementGuid>f94613cb-2dfe-43b4-a8d2-47912b8c515e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='forgot-password-form']/div/div/input</value>
      <webElementGuid>7abaecd5-e332-42d2-8bae-ad39faad9427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>af38d5cc-3058-4573-b92b-f90976bfe4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'forgot-email' and @placeholder = 'Username or Email' and @name = 'email']</value>
      <webElementGuid>7db7fdc7-af0d-4b86-861d-2c96bb7e7f35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
