<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Re-enter Password</name>
   <tag></tag>
   <elementGuidId>6bf99dda-6b10-4c31-ab00-12994de2286f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'password' and @id = 'Confirm-password' and @placeholder = 'Re-enter Password' and @name = 'confirmPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Confirm-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Confirm-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d604458-cf00-4439-9423-fccbef96f2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>aa79c3bb-c4f9-430c-a098-5cf156fa66cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Confirm-password</value>
      <webElementGuid>2359cde1-d28b-486a-9fe7-712a6c704c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Re-enter Password</value>
      <webElementGuid>1f42ce9f-542e-4633-9b1c-4418e97f150f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>85b56b98-04b5-4a36-a32d-56fe24a87913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9T55T</value>
      <webElementGuid>657c33be-420e-4f25-9d4f-371c67a19366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Confirm-password&quot;)</value>
      <webElementGuid>718484ce-adbc-46b5-a517-7f97466c85cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Confirm-password']</value>
      <webElementGuid>00568057-05ca-4e58-9d44-d16e8871287e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup-form']/div[5]/div[3]/div/input</value>
      <webElementGuid>16f6cd92-0c75-4455-aecb-426e88f3b10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>3c88e9f9-e21f-4532-8207-26365b2ffce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'Confirm-password' and @placeholder = 'Re-enter Password' and @name = 'confirmPassword']</value>
      <webElementGuid>affb2311-d484-481e-8adb-5364e2d92891</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
