<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pronouns (optional)</name>
   <tag></tag>
   <elementGuidId>02e69a2a-5cbd-4292-a14f-32c8cbe4646c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pronouns</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pronouns']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d4b56896-6d32-431a-968c-9204925554b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pronouns</value>
      <webElementGuid>365ff4d8-0856-4aad-911c-01f7ec2377b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pronouns</value>
      <webElementGuid>70584818-b97d-4b15-89b0-2809196c40d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>C5Y3- _9jNr0</value>
      <webElementGuid>ea689d3d-dee7-4736-8000-3825cbaea812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pronouns (optional)He/HimShe/HerThey/ThemNot listedPrefer not to say</value>
      <webElementGuid>bb162048-bd7d-4cb1-b6a0-56a4f62a906e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pronouns&quot;)</value>
      <webElementGuid>77c9866f-b725-4463-9ae5-d019a4aee73c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pronouns']</value>
      <webElementGuid>105e484d-559f-42b0-ac20-1d4734321a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup-form']/div[4]/div/select</value>
      <webElementGuid>6a4b6963-bb13-4b98-b281-39008371b711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pronouns (optional)'])[1]/following::select[1]</value>
      <webElementGuid>4300fa9b-5bf6-4a15-9de7-008928e2949a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birthday'])[1]/following::select[4]</value>
      <webElementGuid>489e19b0-996c-43cb-a18c-0b065f26c5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::select[1]</value>
      <webElementGuid>674b6bb0-9070-48d2-a663-181d1eb70ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show'])[1]/preceding::select[1]</value>
      <webElementGuid>f5b5ada4-cb0c-4c0f-952a-579eb98172e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>0b9b918d-0308-4e9d-a102-4236330f2c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pronouns' and @name = 'pronouns' and (text() = 'Pronouns (optional)He/HimShe/HerThey/ThemNot listedPrefer not to say' or . = 'Pronouns (optional)He/HimShe/HerThey/ThemNot listedPrefer not to say')]</value>
      <webElementGuid>e7ff2d35-84ea-4d8b-ba61-2c88463880e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
