<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Wattpad programs  opportunities</name>
   <tag></tag>
   <elementGuidId>176f233a-742b-44a3-8a28-d9d1f9721e84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'https://creators.wattpad.com/programs-and-opportunities/' and (text() = 'Wattpad programs &amp; opportunities' or . = 'Wattpad programs &amp; opportunities')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='writer-opportunities-dropdown']/div[2]/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>30529ff6-d8eb-4e47-a4ee-b405220fd491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c97t-</value>
      <webElementGuid>07bd372e-5e12-46e9-9882-e7f8bbb3a099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://creators.wattpad.com/programs-and-opportunities/</value>
      <webElementGuid>965d1398-20c3-4cd1-9ba2-7d0248ce6a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>ae35788a-c502-4d4f-8ded-677fa3038378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>fe41aca3-f43b-4014-9112-ada8d10303f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wattpad programs &amp; opportunities</value>
      <webElementGuid>90656205-0cd2-41f3-b06b-e329de722ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;writer-opportunities-dropdown&quot;)/div[@class=&quot;MaVh4 V-8Oa M33oU&quot;]/ul[@class=&quot;_0X2RS&quot;]/li[@class=&quot;fnWge&quot;]/a[@class=&quot;c97t-&quot;]</value>
      <webElementGuid>21af1b9e-6253-4731-a720-68965e5ab438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='writer-opportunities-dropdown']/div[2]/ul/li[4]/a</value>
      <webElementGuid>5198d7f4-c8b2-4dc1-9af1-7a821abbaa4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Wattpad programs &amp; opportunities')]</value>
      <webElementGuid>34523e4b-06fb-4c61-8946-bfc9ae5dcef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Helpful writer resources'])[1]/following::a[1]</value>
      <webElementGuid>9b7af742-f8f9-4917-b541-ad0acfd40d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write'])[1]/following::a[4]</value>
      <webElementGuid>cac2051c-d09f-4473-bdf9-aad5ea8fe9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Writing contests'])[1]/preceding::a[1]</value>
      <webElementGuid>47ab320a-b84d-4e70-a245-623f524cc690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Premium'])[1]/preceding::a[2]</value>
      <webElementGuid>7014c58a-6aaf-4b8b-a4df-d03faee78c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wattpad programs &amp; opportunities']/parent::*</value>
      <webElementGuid>536bf991-8c76-4211-8e1f-598eb1ced876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://creators.wattpad.com/programs-and-opportunities/')]</value>
      <webElementGuid>12b3985f-f03d-45a4-bb88-16b05d2224f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>943befc0-ff3f-4d81-b985-01b6e8455eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://creators.wattpad.com/programs-and-opportunities/' and (text() = 'Wattpad programs &amp; opportunities' or . = 'Wattpad programs &amp; opportunities')]</value>
      <webElementGuid>b5e07802-247d-46cd-b536-38528c997381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
