<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Editors Picks</name>
   <tag></tag>
   <elementGuidId>df73ac55-48c0-450c-afe0-8fa2ba12f74a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = 'https://www.wattpad.com/list/551324301' and (text() = concat(&quot;Editor&quot; , &quot;'&quot; , &quot;s Picks&quot;) or . = concat(&quot;Editor&quot; , &quot;'&quot; , &quot;s Picks&quot;))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='discover-dropdown']/div[2]/div/ul/li[13]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0765f6b7-66f9-4aec-865b-ff6da59f9004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c97t-</value>
      <webElementGuid>4e955135-8256-42e1-8848-16b41bd08b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.wattpad.com/list/551324301</value>
      <webElementGuid>41e0f844-0539-4d55-aeb5-5a7ff734c384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>471c80f9-61dd-4bad-a4fd-dcbda87f44f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>16d7bfb8-f0b3-4a80-95be-54da91b8386e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Editor's Picks</value>
      <webElementGuid>bcf2640f-8784-4895-a0c4-619dc48cab03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;discover-dropdown&quot;)/div[@class=&quot;MaVh4 V-8Oa MllQ5&quot;]/div[@class=&quot;zCGIO&quot;]/ul[@class=&quot;_0X2RS&quot;]/li[@class=&quot;fnWge&quot;]/a[@class=&quot;c97t-&quot;]</value>
      <webElementGuid>d58edcd7-95d8-4215-913d-6e823572440f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='discover-dropdown']/div[2]/div/ul/li[13]/a</value>
      <webElementGuid>5f85e870-d837-4d72-aa4e-f1cbfafcb22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paranormal'])[1]/following::a[1]</value>
      <webElementGuid>01675539-2a00-4930-b373-074cbffffb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Historical Fiction'])[1]/following::a[2]</value>
      <webElementGuid>aa6e051f-3483-47ed-90b5-e8291a768775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Humor'])[1]/preceding::a[1]</value>
      <webElementGuid>42a95d5c-5af4-4573-bde6-0e250d9864ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Horror'])[1]/preceding::a[2]</value>
      <webElementGuid>d2941692-6db9-4bed-aa5f-76a7d4047ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.wattpad.com/list/551324301')]</value>
      <webElementGuid>0d2c0551-4211-4ed8-b2d7-f39270f13d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]/a</value>
      <webElementGuid>b128c70a-5149-430e-b807-5216f1834e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.wattpad.com/list/551324301' and (text() = concat(&quot;Editor&quot; , &quot;'&quot; , &quot;s Picks&quot;) or . = concat(&quot;Editor&quot; , &quot;'&quot; , &quot;s Picks&quot;))]</value>
      <webElementGuid>96d0a4ba-25b3-45cd-89e6-57637de5b4b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
