<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Horror</name>
   <tag></tag>
   <elementGuidId>624b529b-96a5-44aa-9d38-28e1fba5ed17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = 'https://www.wattpad.com/stories/horror' and (text() = 'Horror' or . = 'Horror')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='discover-dropdown']/div[2]/div/ul/li[15]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>72b7ca29-b165-4a59-ba54-accbfdb21d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c97t-</value>
      <webElementGuid>57b3acab-3f70-4235-a5bd-db0c4d66adca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.wattpad.com/stories/horror</value>
      <webElementGuid>acb6093f-3a59-46e6-a0a4-4c286bc69dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>407a936f-028b-4131-a4d2-8e78101de4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>d70faac4-fa66-4ea7-b57c-ba891f15d673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Horror</value>
      <webElementGuid>790db80f-078d-4821-88e2-5443bca43f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;discover-dropdown&quot;)/div[@class=&quot;MaVh4 V-8Oa MllQ5&quot;]/div[@class=&quot;zCGIO&quot;]/ul[@class=&quot;_0X2RS&quot;]/li[@class=&quot;fnWge&quot;]/a[@class=&quot;c97t-&quot;]</value>
      <webElementGuid>d9121fa1-7238-46bd-9adb-06d61774cdc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='discover-dropdown']/div[2]/div/ul/li[15]/a</value>
      <webElementGuid>d9327e43-a592-486f-9ef7-a8f90d9685a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Horror')]</value>
      <webElementGuid>2b9ec326-88e5-4e5a-af27-8323164c3f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Humor'])[1]/following::a[1]</value>
      <webElementGuid>94a98bf4-4c3a-41a6-97e3-d9ce318706b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contemporary Lit'])[1]/preceding::a[1]</value>
      <webElementGuid>12e078b9-ff2e-440b-a890-988f32cb22fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diverse Lit'])[1]/preceding::a[2]</value>
      <webElementGuid>96361144-b27a-4c02-8f1a-7938d7b26630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Horror']/parent::*</value>
      <webElementGuid>fe086898-ab71-4085-bc7b-1dad67bf48fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.wattpad.com/stories/horror')]</value>
      <webElementGuid>06661dc0-b06f-4d01-ad7d-60ed798b0ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[15]/a</value>
      <webElementGuid>8c1a43c5-e4de-4856-8360-8eaedaceaeb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.wattpad.com/stories/horror' and (text() = 'Horror' or . = 'Horror')]</value>
      <webElementGuid>fbd2ce9c-03ad-465e-a558-a540837aaa7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
